-- Audit trail and data conventions.
--
-- Adds the append-only `audit_logs` table that every later phase writes to, so
-- an administrative action can always be attributed to a person, a request and
-- a moment.
--
-- Timestamp convention for this table (and every table added from here on):
-- ISO-8601 UTC with milliseconds, `YYYY-MM-DDTHH:MM:SS.sssZ`, generated by the
-- APPLICATION (`nowIso()`), never by `datetime('now')`. The format is
-- fixed-width, so the `created_at` index gives chronological ordering directly.
--
-- No existing table is modified. `attendees`, `raffle_draws`, `admin_users`,
-- `admin_sessions` and `admin_login_attempts` are untouched.

CREATE TABLE audit_logs (
  id TEXT PRIMARY KEY CHECK (length(id) > 0),

  -- NULLABLE on purpose: a failed login is audited before any actor exists.
  -- ON DELETE SET NULL (never CASCADE) so removing an administrator can never
  -- erase the history of what they did — the row survives, orphaned but intact.
  actor_admin_id TEXT REFERENCES admin_users(id) ON DELETE SET NULL,

  action TEXT NOT NULL CHECK (length(action) > 0 AND length(action) <= 64),
  entity_type TEXT NOT NULL CHECK (length(entity_type) > 0 AND length(entity_type) <= 48),
  entity_id TEXT,

  -- Nullable and WITHOUT a foreign key: `events` does not exist until a later
  -- phase. The column is added now so audit rows written before then can still
  -- be filtered by event once it does.
  event_id TEXT,

  -- Serialized JSON. Validation lives in the application (`parseJson`), not in
  -- a CHECK: D1 offers no dependable JSON validity predicate, and a brittle
  -- constraint here would reject rows the application considers fine.
  previous_data TEXT,
  new_data TEXT,
  metadata TEXT,

  -- SHA-256 of the client IP. The raw address is never persisted.
  ip_hash TEXT,
  user_agent TEXT CHECK (user_agent IS NULL OR length(user_agent) <= 512),

  request_id TEXT NOT NULL CHECK (length(request_id) > 0 AND length(request_id) <= 64),

  -- Exactly 24 characters: YYYY-MM-DDTHH:MM:SS.sssZ. The length check is a
  -- cheap guard that keeps a naive `datetime('now')` value (19 chars, no zone)
  -- from ever entering this column and corrupting lexicographic ordering.
  created_at TEXT NOT NULL CHECK (length(created_at) = 24 AND created_at LIKE '____-__-__T__:__:__.___Z')
);

-- Listing is ordered by recency, which is also the default view.
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_actor_admin_id ON audit_logs(actor_admin_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_event_id ON audit_logs(event_id);
CREATE INDEX idx_audit_logs_request_id ON audit_logs(request_id);

-- Composite: "everything that happened to this entity", the common drill-down.
-- created_at trails the key so the per-entity view is already ordered.
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);

-- Immutability is enforced by the application: AuditRepository exposes only
-- `append`, `list` and `findById`, and no endpoint offers UPDATE or DELETE.
-- It is deliberately NOT enforced with SQL triggers, which would also block the
-- legitimate retention/redaction work a later phase may need to perform through
-- a migration.
