-- Event domain.
--
-- A NEW, independent domain. It deliberately shares nothing with the legacy
-- lead-capture code: the `attendees` table, the `/events` public route and the
-- migration named `0004_events_lead_fields.sql` all predate this and describe
-- insurance/marketing leads. The word "events" in those names is a coincidence
-- of history, not a domain.
--
-- Timestamps follow the phase 2 convention: ISO-8601 UTC with milliseconds,
-- generated by the application, fixed width so ordering is chronological.

CREATE TABLE events (
  id TEXT PRIMARY KEY CHECK (length(id) > 0),

  -- Public identifier. Lowercase, hyphenated, unique, and never colliding with
  -- a reserved route (enforced in the application, which owns the route list).
  slug TEXT NOT NULL UNIQUE CHECK (length(slug) > 0 AND length(slug) <= 80),
  name TEXT NOT NULL CHECK (length(trim(name)) > 0 AND length(name) <= 160),

  description TEXT,
  banner_url TEXT,
  location_name TEXT,

  -- IANA identifier, never a numeric offset: offsets change twice a year under
  -- DST, identifiers do not.
  timezone TEXT NOT NULL CHECK (length(timezone) > 0 AND length(timezone) <= 64),

  registration_opens_at TEXT,
  registration_closes_at TEXT,
  starts_at TEXT,
  ends_at TEXT,

  -- Nullable: a draft may not have decided yet. Bounded when present.
  minimum_age INTEGER CHECK (minimum_age IS NULL OR (minimum_age >= 0 AND minimum_age <= 130)),
  max_entries_per_identity INTEGER NOT NULL DEFAULT 1
    CHECK (max_entries_per_identity >= 1 AND max_entries_per_identity <= 1000),

  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
    'DRAFT', 'SCHEDULED', 'OPEN', 'CLOSED',
    'DRAW_READY', 'DRAW_COMPLETED', 'CANCELLED', 'ARCHIVED'
  )),

  confirmation_title TEXT,
  confirmation_message TEXT,
  ineligible_title TEXT,
  ineligible_message TEXT,

  -- Optimistic concurrency token. Every mutation matches on the revision it
  -- read and then increments it, so a slow editor cannot silently overwrite a
  -- change made after their form was loaded.
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),

  -- Attribution. RESTRICT, never CASCADE or SET NULL: deleting an
  -- administrator must not delete their events, nor quietly erase who created
  -- them. Removing an admin who owns events is a deliberate operational
  -- decision that has to be resolved explicitly.
  created_by TEXT NOT NULL REFERENCES admin_users(id) ON DELETE RESTRICT,
  updated_by TEXT NOT NULL REFERENCES admin_users(id) ON DELETE RESTRICT,

  created_at TEXT NOT NULL
    CHECK (length(created_at) = 24 AND created_at LIKE '____-__-__T__:__:__.___Z'),
  updated_at TEXT NOT NULL
    CHECK (length(updated_at) = 24 AND updated_at LIKE '____-__-__T__:__:__.___Z'),

  -- Operational timestamps, written only by their lifecycle action.
  published_at TEXT,
  opened_at TEXT,
  closed_at TEXT,
  cancelled_at TEXT,
  archived_at TEXT
);

-- `slug` already carries a UNIQUE index from the column constraint
-- (sqlite_autoindex_events_1), which serves lookups by slug; no second index is
-- created for it.
CREATE INDEX idx_events_status ON events(status);
CREATE INDEX idx_events_created_at ON events(created_at DESC);
CREATE INDEX idx_events_updated_at ON events(updated_at DESC);
CREATE INDEX idx_events_archived_at ON events(archived_at);

-- Window lookups: "what is open now" and "what runs during this period".
CREATE INDEX idx_events_registration_window
  ON events(registration_opens_at, registration_closes_at);
CREATE INDEX idx_events_event_window ON events(starts_at, ends_at);

-- Listing is filtered by status and ordered by recency far more often than
-- anything else; this composite serves that path directly.
CREATE INDEX idx_events_status_created_at ON events(status, created_at DESC);
